language: python

addons:
  apt:
    update: true
    packages:
    - wget 
    - libspatialindex-dev 
    - libglu1
    - libxrender1
    - libxtst6
    - libxi6
    
before_install:
  - wget https://download.blender.org/release/Blender2.79/blender-2.79b-linux-glibc219-x86_64.tar.bz2
  - tar xjf blender-2.79b-linux-glibc219-x86_64.tar.bz2
  - mv blender-2.79b-linux-glibc219-x86_64 /usr/local
  - export PATH=/usr/local/blender-2.79b-linux-glibc219-x86_64:$PATH
  
script:
  - py.test
