language: python

services:
  - docker

script:
- docker build -t gregstarr/pychop3d .
- docker run gregstarr/pychop3d /bin/bash -c "git clone https://github.com/gregstarr/pychop3d.git; cd pychop3d; py.test"
