language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    update: true
    packages:
    - wget 
    - libspatialindex-dev 
    - libglu1
    - libxrender1
    - libxtst6
    - libxi6
    
before_install:
  - cd ..
  - wget https://download.blender.org/release/Blender2.79/blender-2.79b-linux-glibc219-x86_64.tar.bz2
  - tar xjf blender-2.79b-linux-glibc219-x86_64.tar.bz2
  - export PATH=/home/travis/build/gregstarr/blender-2.79b-linux-glibc219-x86_64:$PATH
  - export PYTHONPATH=/home/travis/build/gregstarr/pychop3d
  - cd pychop3d
  
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - travis_wait 30 coverage run --source=pychop3d -m pytest test/
  
notifications:
  email:
    on_success: never
    on_failure: never
after_success:
  - coveralls
