import numpy as np

PRINTER_EXTENTS = np.array([150, 150, 150], dtype=float)
PLANE_SPACING = 20
N_RANDOM_NORMALS = 40
SUFFICIENTLY_DIFFERENT_THRESHOLD = .1 * np.sqrt(np.sum(PRINTER_EXTENTS ** 2))

# objective weightings
A_PART = 1
A_UTIL = .25
A_CONNECTOR = 1
A_FRAGILITY = 1
A_SEAM = .1
A_SYMMETRY = .25

FRAGILITY_THRESHOLD = .95

CONNECTOR_DIAMETER = 10
CONNECTOR_OBJECTIVE_THRESHOLD = 10

EPSILON = 1e-6
