import numpy as np
import trimesh

PRINTER_EXTENTS = np.array([180, 180, 180], dtype=float)
PLANE_SPACING = 30
N_THETA = 5
N_PHI = 5

SUFFICIENTLY_DIFFERENT_THRESHOLD = .1 * np.sqrt(np.sum(PRINTER_EXTENTS ** 2))

# objective weightings
A_PART = 1
A_UTIL = .25
A_CONNECTOR = 1
A_FRAGILITY = 1
A_SEAM = .1
A_SYMMETRY = .25

CONNECTOR_COLLISION_WEIGHT = 10**10

FRAGILITY_THRESHOLD = .95

CONNECTOR_DIAMETER = 10
CONNECTOR_TOLERANCE = 1
CONNECTOR_OBJECTIVE_THRESHOLD = 10

EPSILON = 1e-6

CH_SAMPLE_POINTS = trimesh.primitives.Sphere(radius=1000).vertices

INITIAL_CONNECTOR_RATIO = .1
INITIALIZATION_ITERATIONS = 15_000
ANNEALING_ITERATIONS = 300_000
